- hosts: cassandra_servers
  tasks: 

  - name: Send host informations to Slack
    slack:
     token: "T029AES6D/x/x"
     msg: '{{ ansible_ssh_host }} {{ hostvars[inventory_hostname]["ansible_default_ipv4"]["address"] }} Cassandra kurulumu tamamlandi. PMM kurulumu gerceklestirildi. User: cassandra Password: cassandra  '
     channel: #nazelintest
     color: good
     username: ''
     icon_url: ''
